#!/usr/bin/env python

# Copyright (C) Pipin Fitriadi - All Rights Reserved

# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 1 January 2025

# Generated by Django 5.1.4 on 2025-01-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                (
                    'id',
                    models.BigIntegerField(primary_key=True, serialize=False)
                ),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('img_path', models.TextField()),
                ('duration', models.SmallIntegerField()),
                ('genre', models.JSONField(default=list)),
                ('language', models.TextField()),
                ('mpaa_rating', models.JSONField(default=dict)),
                ('user_rating', models.TextField()),
            ],
        ),
    ]
